"""Throwaway no-op macros for package macros that no adapter dispatch can reach.

``adapter.dispatch('create_primary_key', 'dbt_constraints')`` searches, in order,
``<root_project>.<adapter>__create_primary_key``,
``<root_project>.default__create_primary_key``,
``dbt_constraints.<adapter>__create_primary_key`` and finally
``dbt_constraints.default__create_primary_key``. Packages that ship warehouse
specific macros only -- ``dbt_constraints`` has ``snowflake__…`` but no
``default__…`` -- therefore have no candidate at all under the DuckDB profile the
sqlfluff hooks template with, and compilation fails with "In dispatch: No macro
named …".

The helpers here close that gap for the duration of a hook run by writing a stub
macro named ``<adapter>__<name>`` into the offending package's own ``macros/``
directory, which is the fourth candidate above. Two details make that safe:

* The stub is *adapter prefixed*, never ``default__``. A ``default__`` stub would
  be found before ``dbt_constraints.snowflake__create_primary_key`` on a real
  Snowflake run and silently replace the genuine implementation; an
  ``duckdb__`` one is unreachable unless the target really is DuckDB.
* The stub lands under ``dbt_packages/``, which is untracked and regenerated by
  ``dbt deps``, so the consumer's own files are never touched.

Stubs take no declared arguments. A Jinja macro that merely *references*
``varargs`` and ``kwargs`` accepts any call signature, so the real signature never
has to be parsed out of the package.
"""

from __future__ import annotations

import re
from collections.abc import Iterator
from contextlib import contextmanager
from pathlib import Path

from dbt_precommit_hooks.profiles import read_project

DEFAULT_PACKAGES_PATH = "dbt_packages"
SHIM_FILENAME = "_dbt_precommit_dispatch_shims.sql"

#: Prefixes treated as an adapter dispatch variant. Macro names may contain a
#: double underscore for other reasons, and stubbing those would be noise.
KNOWN_ADAPTER_PREFIXES = frozenset(
    {
        "athena",
        "bigquery",
        "clickhouse",
        "databricks",
        "duckdb",
        "fabric",
        "postgres",
        "redshift",
        "snowflake",
        "spark",
        "sqlserver",
        "synapse",
        "trino",
    }
)

MACRO_RE = re.compile(r"{%-?\s*macro\s+([a-zA-Z_]\w*?)__([a-zA-Z_]\w*)\s*\(")

SHIM_HEADER = (
    "{#\n"
    "    Generated by dbt-precommit-hooks and deleted when the hook finishes.\n"
    "    No-op stubs so adapter.dispatch resolves under the throwaway CI profile.\n"
    "#}\n"
)

SHIM_MACRO = """
{{% macro {prefix}__{name}() %}}
    {{%- set _ = varargs %}}{{% set _ = kwargs -%}}
    {{{{ return('') }}}}
{{% endmacro %}}
"""


def packages_dir(project_dir: Path) -> Path:
    """Return the directory ``dbt deps`` installs packages into."""
    project = read_project(project_dir / "dbt_project.yml")
    install_path = project.get("packages-install-path") or DEFAULT_PACKAGES_PATH
    return project_dir / str(install_path)


def package_macro_dir(package: Path) -> Path | None:
    """Return the directory a package keeps its macros in, if it has one.

    Almost every package uses the ``macros/`` default, but ``macro-paths`` is a
    package-level setting and a shim written outside it would never be parsed.
    """
    project_file = package / "dbt_project.yml"
    macro_paths = ["macros"]
    if project_file.is_file():
        declared = read_project(project_file).get("macro-paths")
        if declared:
            macro_paths = [str(path) for path in declared]

    return next((package / path for path in macro_paths if (package / path).is_dir()), None)


def _prefixed_macros(macros_dir: Path) -> dict[str, set[str]]:
    """Map every dispatch prefix found under ``macros_dir`` to its macro names."""
    found: dict[str, set[str]] = {}
    for sql_file in sorted(macros_dir.rglob("*.sql")):
        text = sql_file.read_text(encoding="utf-8", errors="replace")
        for prefix, name in MACRO_RE.findall(text):
            if prefix == "default" or prefix in KNOWN_ADAPTER_PREFIXES:
                found.setdefault(prefix, set()).add(name)
    return found


def find_dispatch_gaps(packages_dir: Path, adapter: str) -> dict[Path, list[str]]:
    """Return the macro names each installed package dispatches but cannot serve.

    A gap is a macro that exists under some adapter prefix but under neither
    ``default__`` nor ``<adapter>__``, which is exactly the case dispatch fails on.
    """
    if not packages_dir.is_dir():
        return {}

    gaps: dict[Path, list[str]] = {}
    for package in sorted(p for p in packages_dir.iterdir() if p.is_dir()):
        macros_dir = package_macro_dir(package)
        if macros_dir is None:
            continue

        by_prefix = _prefixed_macros(macros_dir)
        servable = by_prefix.get("default", set()) | by_prefix.get(adapter, set())
        missing = {
            name for prefix, names in by_prefix.items() if prefix != "default" for name in names
        } - servable
        if missing:
            gaps[macros_dir] = sorted(missing)
    return gaps


def render_shims(names: list[str], adapter: str) -> str:
    """Return the body of a shim file defining a no-op stub for each name."""
    stubs = "".join(SHIM_MACRO.format(prefix=adapter, name=name) for name in names)
    return SHIM_HEADER + stubs


@contextmanager
def dispatch_shims(project_dir: Path, adapter: str) -> Iterator[list[Path]]:
    """Write shim files for unreachable dispatches, then remove them again.

    Yields the paths written, which is empty when no packages are installed or
    every dispatched macro already has an implementation the adapter can reach.
    """
    written: list[Path] = []
    try:
        for macros_dir, names in find_dispatch_gaps(packages_dir(project_dir), adapter).items():
            shim_file = macros_dir / SHIM_FILENAME
            # A leftover from a killed run is still a valid shim, and deleting a
            # file this run did not create would be a surprise.
            if shim_file.exists():
                continue
            shim_file.write_text(render_shims(names, adapter), encoding="utf-8")
            written.append(shim_file)
        yield written
    finally:
        for shim_file in written:
            shim_file.unlink(missing_ok=True)
